### ISSUE TITLE
Create keyboard shortcuts to open different widgets 

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#733]
We need keyboard shortcuts to create navigation and opening of widgets more easily.
I'd suggest stick to the most famous keyboard shortcuts defined by IDA and [x64/Olly]Dbg.

A list of IDA Pro shortcuts can be found here: https://www.hex-rays.com/products/ida/support/freefiles/IDA_Pro_Shortcuts.pdf

**Comment by freshpickle** [comment]
This looks pretty good

**Comment by ITAYC0HEN** [comment]
@freshpickle, that's right! :)
want to take a look?

**Comment by freshpickle** [comment]
Yes would love to...I'm still a high schooler actually but I'm doing a lot
of C++

**Comment by ITAYC0HEN** [comment]
That's great! 

You can start by following the building instructions which are detailed here:
https://radareorg.github.io/cutter/index.html
basically, you need to install QT and build the project.

Here you can see how we have implemented some keyboard shortcuts:
https://github.com/radareorg/cutter/blob/master/src/MainWindow.cpp#L246

The idea is that a keyboard shortcut will bring the relevant widget to focus and open it if it is not opened yet. The PDF I linked in the issue is from IDA Pro software which its free and limited binary can be downloaded from here: https://www.hex-rays.com/products/ida/support/download_freeware.shtml


Come and join us on Telegram or IRC :)
Telegram: https://t.me/r2cutter
#cutter on irc.freenode.net

**Comment by piba941** [comment]
@ITAYC0HEN  i would like to take up this issue.

**Comment by ITAYC0HEN** [comment]
Hi @piba941, love the spirit! Seems like @freshpickle will take this one but we have enough Hacktoberfest issues available: https://github.com/radareorg/cutter/labels/Hacktoberfest

Simply choose one of them and do your magic :)

**Comment by freshpickle** [comment]
You could give it to piba I don't mind..turns out I still don't understand
much but thanks so much for the help

**Comment by ITAYC0HEN** [comment]
okay @piba941 you can go for it! Check my instructions just a few comments above.
Meantime, I'll assign this issue to you :)


@piba941 please check more issues [here](https://github.com/radareorg/cutter/labels/Hacktoberfest), we can walk you through the process - you will do great! :D

**Comment by GordanZovko** [comment]
@ITAYC0HEN is anyone working on this? seems quiet. :) Would like to have a take on this.

**Comment by ITAYC0HEN** [comment]
@GordanZovko please do :) Indeed seems quiet.
would appreciate if you'll take and finish it actually :)

thanks!

**Comment by GordanZovko** [comment]
@ITAYC0HEN I am a bit lost, are there defined functions that need to be bound to shortcuts, if so can you please point some of them to me?

**Comment by ITAYC0HEN** [comment]
hi @GordanZovko! Please see my comment above https://github.com/radareorg/cutter/issues/733#issuecomment-425870240

For example, `Shift +  F12` should bring to focus the Strings widget (list of shortcuts available in the link I posted at the head of this thread) and will open it if it's not opened.

**Comment by icebp** [comment]
@ITAYC0HEN  is anyone working on it? I looked at the code a bit and I think I can create a PR today adding these shortcuts (at least the widgets ones)
